const projectsData = [
  {
    image: "/coinspe1.png",
    name: "CoinsPe",
    href: "https://coinspe.com/",
    techstack: [
      "Next.js",
      "Node.js",
      "Express.js",
      "PostgreSQL",
      "Redis",
      "TradingView Charts",
      "Redux",
      "Socket.IO",
      "TypeScript",
      "Tailwind CSS",
      "Minio Cloud",
    ],
    details: `A cutting-edge cryptocurrency platform for secure and efficient digital asset transactions. At Subhx Infotech, I contributed by developing scalable backend architecture, implementing auto KYC verification, and ensuring a responsive, high-performance frontend. The platform offers advanced features for crypto trading and portfolio management.`,
  },
  {
    image: "/hirup.png",
    name: "Subhux HireUp",
    href: "https://hireup.subhx.in/",
    techstack: [
      "Next.js",
      "Node.js",
      "Express.js",
      "PostgreSQL",
      "Socket.IO",
      "TypeScript",
      "Tailwind CSS",
      "Minio Cloud",
    ],
    details: `A career platform for managing recruitment at Subhx Infotech. Applicants can apply online, and HR/management review applications and generate interview links. Powered by Subhx.ai, it conducts AI-driven, time-limited interviews with auto-submission, generates PDF assessment reports, and provides HR with access to answers, screen recordings, and secure activity monitoring.`,
  },
  {
    image: "/subhx.png",
    name: "Subhx Infotech",
    href: "https://subhx.in/",
    techstack: ["Next.js", "TypeScript", "Metirial UI", "Tailwind CSS"],
    details: `Official website of Subhx Infotech. I redesigned and updated its UI to create a modern, visually appealing, and user-friendly interface. The redesign focused on improving navigation, responsiveness, and overall user experience while aligning the design with the company’s brand identity.`,
  },
  {
    image: "/freshcheck.png",
    name: "FreshCheck - Hotel Food Quality Monitoring System",
    href: "https://fresh-check-sigma.vercel.app",
    github: "https://github.com/AshiqueGhazali/fresh-check",
    techstack: [
      "Next.js",
      "TypeScript",
      "Node.js",
      "Express.js",
      "MySQL",
      "Prisma ORM",
      "Tailwind CSS",
      "Shadcn UI",
      "Google Gemini AI",
    ],
    details: `FreshCheck is a full-stack hotel food quality monitoring system designed to digitize inspection workflows and improve compliance. The platform features role-based access control for inspectors and management, dynamic inspection forms, report approvals, and AI-powered summaries using Google Gemini AI. Built with modern web technologies, it delivers real-time insights, scalable architecture, and a polished enterprise-grade UI.`,
  },

  {
    image: "/veew.png",
    name: "VEEW - Virtual Event Hosting Platform",
    href: "https://github.com/AshiqueGhazali/Veew-frontend",
    techstack: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Socket.IO",
      "WebRTC",
      "TypeScript",
      "Tailwind CSS",
    ],
    details: `Veew is a Virtual Event Hosting platform that enables seamless online event experiences by integrating live streaming, interactive sessions, attendee networking, and customizable event spaces. Built with MongoDB, Express.js, React.js, and Node.js, it delivers a scalable, high-performance full-stack solution designed for immersive virtual engagement and collaboration.`,
  },
  {
    image: "/zephyr.png",
    name: "ZEPHYR - E-commerce Platform",
    href: "https://github.com/AshiqueGhazali/Zephyr-",
    techstack: [
      "Node.js",
      "Express.js",
      "MongoDB",
      "Razorpay",
      "AWS",
      "TypeScript",
      "EJS",
      "Bootstrap",
    ],
    details: `A full-featured e-commerce website built with Node.js, Express.js, and MongoDB, offering product purchasing, wallet management, returns, refunds, and coupons. Features an intuitive admin panel for sales, user management, and analytics. Integrated with Razorpay for secure payments and deployed on AWS for performance and scalability.`,
  },
];

export default projectsData;
